# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: thebrainstorm.gr # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Brainstorm
description: "Developing your world!"
keywords: 'jekyll,theme,gem-based,blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: facebook
      url: https://www.facebook.com/Bra1nst0rm
    - name: github
      url: 
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: https://twitter.com/_brainstorm
    - name: vk
      url:
home:
  section1: <h1>Brainstorm</h1>
  section2: <h2>Here lies Brainstorm.</h2>
  section3: <img src="/assets/images/browser.png" alt="logo">   
            <div class="social-links"><a class="ico-facebook btn" href="https://www.facebook.com/Bra1nst0rm" title="Visit us on Facebook" target="_blank"></a><a class="ico-twitter btn" href="https://twitter.com/_brainstorm" title="Follow us on Twitter" target="_blank"></a></div>

apps:
  section1: <h2></h2>
  section2:   
  section3: <div><img src="/assets/images/project/portfolio_01.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_02.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_03.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_04.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_05.jpg" alt="Illuminate" style="width:300px; height:300px;">
            </div>
            <div>
                 <img src="/assets/images/project/portfolio_06.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_07.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_08.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_09.jpg" alt="Illuminate" style="width:300px; height:300px;">
                 <img src="/assets/images/project/portfolio_10.jpg" alt="Illuminate" style="width:300px; height:300px;">
            </div>  
about:
  section1: <h2>Who We Are</h2>
  section2: <div>
                 <p>We believe in Quality over Quantity. We are a newly founded software – and a little bit of hardware – company.</p>
                 <p>We studied Electrical & Computer Engineering at the University of Patras. Passionate Programmers. Maniac Perfectionists.</p>
            </div>
  section3:            
            <div class="container">
             <div class="row">
              <div class="col-md-4 col-sm-4">
               <div class="team-member">
                <div class="team-img">
                 <img src="https://image.freepik.com/free-photo/man-standing-with-a-black-t-shirt_1187-1045.jpg" alt="team member" class="img-responsive">
                </div>
                <div class="team-hover">
                 <div class="desk">
                  <h4>Hi There !</h4>
                  <p>I love to introduce myself as a hardcore Web Designer.</p>
                 </div>
                 <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
                 </div>
                </div>
               </div>
               <div class="team-title">
                <h5>Martin Smith</h5>
                <span>founder &amp; ceo</span>
               </div>
              </div>
              <div class="col-md-4 col-sm-4">
               <div class="team-member">
                <div class="team-img">
                 <img src="https://image.freepik.com/free-photo/elegant-man-with-thumbs-up_1149-1595.jpg" alt="team member" class="img-responsive">
                </div>
                <div class="team-hover">
                 <div class="desk">
                  <h4>Hello World</h4>
                  <p>I love to introduce myself as a hardcore Web Designer.</p>
                 </div>
                 <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
                 </div>
                </div>
               </div>
               <div class="team-title">
                <h5>Franklin Harbet</h5>
                <span>HR Manager</span>
               </div>
              </div>
              <div class="col-md-4 col-sm-4">
               <div class="team-member">
                <div class="team-img">
                 <img src="https://image.freepik.com/free-photo/well-dressed-executive-with-crossed-arms_1098-3930.jpg" alt="team member" class="img-responsive">
                </div>
                <div class="team-hover">
                 <div class="desk">
                  <h4>I love to design</h4>
                  <p>I love to introduce myself as a hardcore Web Designer.</p>
                 </div>
                 <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
                 </div>
                </div>
               </div>
               <div class="team-title">
                <h5>Linda Anderson</h5>
                <span>Marketing Manager</span>
               </div>
              </div>

             </div>

blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: A gem-based responsive simple texture styled <a href="http://jekyllrb.com/">Jekyll</a> theme.

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
