---
title: Brainstorm
timezone: Europe/Athens
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2017-09-30 14:07:00 +3:00
markdown: kramdown
highlighter: rouge
lsi: false
description: your resume
baseurl: "/jekyll-timeline"
url: http://himsel.me
color: "#f2f2f2"
